// Generated by CoffeeScript 1.3.3
var app, assets, express, io, port, socket, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

socket = require('socket.io');

io = socket.listen(app, {
  log: false
});

app = express();

app.use(assets());

app.set('view engine', 'jade');

app.use(express["static"](__dirname + "/../public"));

require('./routes/routes.js')(app, io);

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
