// Generated by CoffeeScript 1.3.3
var app, assets, express, http, io, mongoose, port, server, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/geochat');

app = express();

http = require('http');

server = http.createServer(app);

io = require('socket.io').listen(server, {
  log: false
});

io.configure(function() {
  io.set("transports", ["xhr-polling"]);
  return io.set("polling duration", 10);
});

app.use(assets());

app.set('view engine', 'jade');

app.use(express["static"](__dirname + "/../public"));

require('./routes/routes.js')(app, io);

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

server.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
