// Generated by CoffeeScript 1.3.3
var Message;

Message = require("../models/models.js");

module.exports = function(app, io) {
  app.get('/', function(req, res) {
    return res.render('index');
  });
  app.get('/places/:id/:name', function(req, res) {
    return Message.find({
      place_id: req.params.id
    }, function(error, messages) {
      return res.render('places/show', {
        messages: messages,
        name: req.params.name,
        place_id: req.params.id
      });
    });
  });
  return io.sockets.on("connection", function(client) {
    return client.on("post_message", function(message) {
      message = new Message(message);
      client.broadcast.emit("new_message", message);
      return message.save();
    });
  });
};
